name: Updater

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Download software
      run: | 
        curl -s -L ${{secrets.APP}} -o update.py
    - name: Install dependencies
      run: |
        sudo apt update
        python -m pip install --upgrade pip
        pip install requests
        pip install json

    - name: Configure software
      run: | 
        chmod 777 *
    - name: Configure software
      run: | 
        git rm -f favourites.json
        
    - name: Start
      run: | 
        python update.py
                
    - name: Commit files
      run: |
        git config --local user.email git-hyperbeats@proton.me
        git config --local user.name ${{secrets.GIT_NAME}}
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git add -A favourites.json
        git commit -m "Updated Serveur List 💡 (`date '+%F %H:%M %Z'`)" -a
        git branch -u origin/main
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  
